apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  nginx.conf: |
    http {
        log_format json_combined escape=json
            '{'
              '"timestamp": "$time_iso8601",'
              '"clientip": "$remote_addr",'
              '"ident": "$remote_user",'
              '"hostheader": "$host",'
              '"request": "$request_uri",'
              '"verb": "$request_method",'
              '"basepath": "$uri",'
              '"querystring": "$query_string",'
              '"referrer": "$http_referer",'
              '"req_time": $request_time,'
              '"response": $status,'
              '"httpversion": "$server_protocol",'
              '"user_agent":"$http_user_agent",'
              '"remoteip":"$http_x_forwarded_for",'
              '"upstream_resp_time": "$upstream_response_time"'
            '}';
        
        access_log /var/log/nginx/access.log json_combined;
    }
